### ISSUE TITLE
Web API 用のフレームワークの調査と統合

### ISSUE THREAD

**Issue by a2311kk** [ChubachiPT2024/drump#25]
## 概要

express ？

あるいは、もう少し調べて選定（調査は 12/11 中ぐらいを目途に）

**Comment by shunya9811** [comment]
Expressでいいかもしれないですね。
https://npm-compare.com/ja-JP/express,fastify,koa,nestjs

Node.js単体でも、Web APIを作成できますけど、Expressを使ったほうが、良さそうですかね
https://dev.classmethod.jp/articles/express-js-web-api/
