### ISSUE TITLE
Match 画面の UI コンポーネント配置

### ISSUE THREAD

**Issue by a2311kk** [ChubachiPT2024/drump#29]
## 概要

- ヒット、スタンドボタン
- ハンド
- プレイヤー名

など

**Comment by shunya9811** [comment]
https://www.figma.com/design/ANjeizQo8E9F1Ql1gpE2Pt/%E3%83%89%E3%83%A9%E3%83%B3%E3%83%97?node-id=0-1&p=f&t=e1rJgTF4LYIAJoME-0
