### ISSUE TITLE
プロジェクトのセットアップ

### ISSUE THREAD

**Issue by a2311kk** [ChubachiPT2024/drump#6]
### 何をやるのか(目的)
以下の導入
- React 
- tsconfig.json
- テストフレームワーク（Vitest）
- eslint 
- prettier

## 完成の定義

次スプリントで、メンバーが開発できる環境をセットアップする

**Comment by shunya9811** [comment]
## Viteでのプロジェクト作成
https://ja.vite.dev/guide/

**Comment by shunya9811** [comment]
tsconfig.json, tsconfig.app.json and tsconfig.node.json 

https://www.geeksforgeeks.org/why-does-vite-create-multiple-typescript-config-files-tsconfigjson-tsconfigappjson-and-tsconfignodejson/

**Comment by shunya9811** [comment]
# Test
## vitest
https://vitest.dev/guide/

## react testing library
https://testing-library.com/docs/react-testing-library/intro/

## testing library userevent
https://testing-library.com/docs/user-event/install

## 参考
https://tech.kentem.jp/entry/2024/08/06/090000

**Comment by shunya9811** [comment]
## prettier
https://prettier.io/docs/en/install.html
https://tech.kentem.jp/entry/2024/09/19/090000
https://qiita.com/kaitoppp/items/e11701cca96a7d417db8
